DATA:
  DATASET: livec
  BATCH_SIZE: 16
  PATCH_NUM: 10
  CROP_SIZE: (224,224)
SET:
  COUNT: 1162
MODEL:
  TYPE: purevit
  NAME: vit_small_pre
  DROP_PATH_RATE: 0.0
  VIT:
    PATCH_SIZE: 16
    EMBED_DIM: 384
    DEPTH: 12
    NUM_HEADS: 6
    MLP_RATIO: 4
    QKV_BIAS: True
    PRETRAINED: True
    PRETRAINED_MODEL_PATH: /home/data/hrz/IQA-Data-Eff-IQA/deit_3_small_224_1k.pth
    PRETRAINED_MODEL_PATH_t: /home/data/hrz/ICCV-IQA/livec_log/vit_small_pre/NR_livec_posbiHW__e-5_e-7/0/ckpt_epoch_8.pth
#    PRETRAINED_MODEL_PATH_t: /home/data/hrz/ACM_MM/livec_log/vit_small_pre/NR_livec_posbiHW_2/0/ckpt_epoch_5.pth

TRAIN:
  EPOCHS: 10
  WARMUP_EPOCHS: 4
  WEIGHT_DECAY: 0.05
  BASE_LR: 1.0e-4 # 4096 batch-size
  WARMUP_LR: 2.0e-7
  MIN_LR: 2.0e-7
  LR_SCHEDULER:
   NAME: step
   DECAY_EPOCHS: 4
