DATA:
  DATASET: csiq
  BATCH_SIZE: 12
  PATCH_NUM: 10
  CROP_SIZE: (224,224)
SET:
  COUNT: 30
MODEL:
  TYPE: purevit
  NAME: vit_small_pre
  DROP_PATH_RATE: 0.0
  VIT:
    PATCH_SIZE: 16
    EMBED_DIM: 384
    DEPTH: 12
    NUM_HEADS: 6
    MLP_RATIO: 4
    QKV_BIAS: True
    PRETRAINED: True
    PRETRAINED_MODEL_PATH: /home/data/hrz/IQA-Data-Eff-IQA/deit_3_small_224_1k.pth
    PRETRAINED_MODEL_PATH_NAR_teacher: /home/data/hrz/IQA-Data-Eff-IQA/deit_3_small_224_1k.pth
#    PRETRAINED_MODEL_PATH_t: /home/data/hrz/IQA-Data-Eff-IQA/CSIQ_log/vit_small_pre/NRstudent_CSIQ_3/0/ckpt_epoch_6.pth
#    PRETRAINED_MODEL_PATH_t: /home/data/hrz/IQA-Data-Eff-IQA/CSIQ_log/vit_small_pre/NRstudent_CSIQ_3/0/ckpt_epoch_6.pth
    PRETRAINED_MODEL_PATH_t: /home/data/hrz/ICCV-IQA/CSIQ_log/vit_small_pre/NRstudent_CSIQ/13/ckpt_epoch_5.pth
#    PRETRAINED_MODEL_PATH_t: /home/data/hrz/ACM_MM/CSIQ_log/vit_small_pre/NRstudent_CSIQ_t/0/ckpt_epoch_8.pth
    #    PRETRAINED_MODEL_PATH_t: /home/data/hrz/IQA-Data-Eff-IQA/csiq_log/vit_small_pre/NAR_live_posbiHW_12_10/1/ckpt_epoch_5.pth
    PRETRAINED_MODEL_PATH_FR_teahcer: /home/data/hrz/IQA-Data-Eff-IQA/deit_3_small_224_1k.pth
    PRETRAINED_MODEL_PATH_t_196: /home/data/hrz/IQA-Data-Eff-IQA/csiq_log/vit_small_pre/FR_live_posbiHW_12_10/9/ckpt_epoch_7.pth
TRAIN:
  EPOCHS: 9
  WARMUP_EPOCHS: 3
  WEIGHT_DECAY: 0.5
  BASE_LR: 1.0e-4 # 4096 batch-size
  WARMUP_LR: 2.0e-7
  MIN_LR: 2.0e-7
  LR_SCHEDULER:
   NAME: step
   DECAY_EPOCHS: 3
